// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbmWKqSjPbKBJk2wKieX9ah5F6dSPUqY',
    appId: '1:766659099011:web:25c8f295182b1fa5f39eb6',
    messagingSenderId: '766659099011',
    projectId: 'dev-mynotes-flutter-project',
    authDomain: 'dev-mynotes-flutter-project.firebaseapp.com',
    storageBucket: 'dev-mynotes-flutter-project.appspot.com',
    measurementId: 'G-QF2XY4HWLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVMuCIryLFUw8AwaFwp-prT97shTKGi6I',
    appId: '1:766659099011:android:c215a16f097b2356f39eb6',
    messagingSenderId: '766659099011',
    projectId: 'dev-mynotes-flutter-project',
    storageBucket: 'dev-mynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB18ADZ3ZI7PazcyIpSHcuclUo5IB9IBT4',
    appId: '1:766659099011:ios:0722b48b206b2cf2f39eb6',
    messagingSenderId: '766659099011',
    projectId: 'dev-mynotes-flutter-project',
    storageBucket: 'dev-mynotes-flutter-project.appspot.com',
    iosClientId: '766659099011-j2829s9ssosk8hisqtlnl0p1ct7i99t9.apps.googleusercontent.com',
    iosBundleId: 'com.developer.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB18ADZ3ZI7PazcyIpSHcuclUo5IB9IBT4',
    appId: '1:766659099011:ios:0722b48b206b2cf2f39eb6',
    messagingSenderId: '766659099011',
    projectId: 'dev-mynotes-flutter-project',
    storageBucket: 'dev-mynotes-flutter-project.appspot.com',
    iosClientId: '766659099011-j2829s9ssosk8hisqtlnl0p1ct7i99t9.apps.googleusercontent.com',
    iosBundleId: 'com.developer.mynotes',
  );
}
